### ISSUE TITLE
👩‍💻 Icon for Qt files is missing

### ISSUE THREAD

**Issue by asmaamirkhan** [BeardedBear/bearded-icons#52]
Hi 🙋‍♀️,

Thank you for the great themes ✨! 

I noticed that icons of [Qt](https://www.qt.io/) projects' files are missing. Specifically; `.pro`, `.pro.user` and `.ui`

![image](https://user-images.githubusercontent.com/45575570/141673167-d2e7a103-089c-4b4b-82b7-80a883402a60.png)

> 📝 Used theme: Bearded Theme Earth 🚀

**Comment by BeardedBear** [comment]
Hey! 

I had to work around the problem, because the .pro extension is the one used in many cases, but especially for the Prolog language : https://en.wikipedia.org/wiki/Prolog so I chose to make an icon for Prolog instead... 

For the .pro.user extension, I didn't find any specific resource about it, so I created a simple user icon ;)

**Comment by asmaamirkhan** [comment]
Great! 🎉
Thank you very much ✨
