### ISSUE TITLE
[Request]: .feature File Icon

### ISSUE THREAD

**Issue by burakkaygusuz** [BeardedBear/bearded-icons#76]
The icon is missing for feature extension files. This extension belongs to [cucumber](https://cucumber.io) tool. Could you please add it? Thanks.

**Comment by BeardedBear** [comment]
Note for me : also adding cucumber config files 
- cucumber.yml
- cucumber.yaml
- cucumber.js
- cucumber.cjs
- cucumber.mjs
- cucumber.json

**Comment by burakkaygusuz** [comment]
.feature extension files look like this. Why doesn't it look like cucumber config files?

![ss](https://user-images.githubusercontent.com/17873574/185846807-38c11d69-d9d2-4a05-bc5a-0940663f3aa9.png)

**Comment by BeardedBear** [comment]
Because I don't know this techno very well, so after doing some research I thought it was files used to create test series, so I put a vial like the one for unit tests that I have in JS/TS for example, but in the color of the cucumber logo, but if you tell me that it's disturbing or that I understood wrong, no worries I fix it ^^

**Comment by burakkaygusuz** [comment]
Thanks for your reply. It looks like a unit test file, but in short, the files with the "feature" extension are used to actually as documentation files for test automation. I would be pleased if you would like to fix it. :)

**Comment by BeardedBear** [comment]
Done in 0.29.1 version :)
